language: php

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script: ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
